### PR TITLE
Add support for {NL} in kick-message

### PR DESCRIPTION
**Pull request by ANameSpace**
Fix for #29 
Added `{NL}` support for `kick-message`.

### CODE REVIEW

**Comment by UserNugget** [comment]
Hello! Thanks for the PR, but there are some questions:

1) Does a header change should be in this PR?
2) Can you please rename PR to something like "Add support for {NL} in kick-message" to make it easier to track/structurize changes in the future?

**Comment by ANameSpace** [comment]
1. Sorry, I sent this commit to the wrong branch. I'll delete it now.
2. Done.

**Comment by UserNugget** [comment]
Thanks!

**Comment by mdxd44** [comment]
the worst solution possible

**Pull request merged**
